version: '2'
services:
  tmsv1application-app:
    image: tmsv1application
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://tmsv1application-mysql:3306/tmsv1application?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://tmsv1application-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://tmsv1application-elasticsearch:9200
    ports:
      - 8080:8080
  tmsv1application-mysql:
    extends:
      file: mysql.yml
      service: tmsv1application-mysql
  tmsv1application-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: tmsv1application-elasticsearch
